package com.hmdp.enums;

public enum MeetPlanEventType {
    RUN_QUEUED,
    RUN_STARTED,
    AGENT_PLAN_CREATED,
    TOOL_STARTED,
    TOOL_COMPLETED,
    TOOL_FAILED,
    PREFERENCES_READ,
    CONSTRAINTS_CHECKED,
    RESTAURANTS_RECALLED,
    RESTAURANTS_FILTERED,
    PLANS_DRAFTED,
    PLAN_REVIEWED,
    PLANS_VALIDATED,
    WAITING_INPUT,
    RUN_COMPLETED,
    PLAN_CONFIRMED,
    RUN_CANCELLED,
    RUN_FAILED
}
